### ISSUE TITLE
生成的私钥是64位的，如何转成imtoken可以导入的格式

### ISSUE THREAD

**Issue by lailaibtc** [juzi-code/FilecoinJ#7]
生成的私钥是64位的，如何转成imtoken可以导入的格式

**Comment by xuehongyang** [comment]
这个问题我暂时还没解决

**Comment by paipaipaipai** [comment]
![image](https://user-images.githubusercontent.com/30950645/114137435-cbbb3d80-993e-11eb-8394-8bc35d600d34.png)

**Comment by paipaipaipai** [comment]
我使用lotus节点，导出地址私钥格式也是跟imtoken格式一样，这个jar包的私钥格式我觉得可能不适用

**Comment by xuehongyang** [comment]
是的，我也留意到这个问题了。
但是我们主流使用的私钥都是64位，所以我查了不少博客，没找到160位的实现方式，你可以解决这个问题吗？

**Comment by paipaipaipai** [comment]
我找了一天，也没有找到

**Comment by xuehongyang** [comment]
这个问题你解决了吗？

**Comment by geng-hua** [comment]
你好，这个问题解决了吗？生成的私钥是64位的，如何转成imtoken可以导入的格式

**Comment by fzx0824** [comment]
在  createWallet 方法里面添加   
String base64Str = convertToBase64(privatekey);
        String template = "{\"Type\":\"secp256k1\",\"PrivateKey\":\"%s\"}";
        String lotusPrivateKey = strTo16(String.format(template,base64Str));
lotusPrivateKey 能导入到ImToken里面。
另外两个方法如下，希望能帮到大家。
public static String convertToBase64(String str) {
        int length = str.length();
        if(length>64){
            return "";
        }
        if(length<64){
            for (int i = 0; i < (64-length); i++) {
                str = "0"+str;
            }
        }
        char[] strArr = str.toCharArray();
        StringBuffer sb = new StringBuffer();
        byte[] bytes = new byte[32];
        int i = 0;
        for (char ch : strArr){
            sb.append(ch);
            if(sb.toString().length()>1){
                byte info = (byte)Integer.parseInt(sb.toString(),16);
                bytes[i] = info;
                i++;
                sb = new StringBuffer();
            }
        }
        return Base64.encode(bytes);
    }
    public static String strTo16(String s) {
        String str = "";
        for (int i = 0; i < s.length(); i++) {
            int ch = (int) s.charAt(i);
            String s4 = Integer.toHexString(ch);
            str = str + s4;
        }
        return str;
    }
    有其他问题大家在一起沟通。

**Comment by paipaipaipai** [comment]
> 在 createWallet 方法里面添加
> String base64Str = convertToBase64(privatekey);
> String template = "{"Type":"secp256k1","PrivateKey":"%s"}";
> String lotusPrivateKey = strTo16(String.format(template,base64Str));
> lotusPrivateKey 能导入到ImToken里面。
> 另外两个方法如下，希望能帮到大家。
> public static String convertToBase64(String str) {
> int length = str.length();
> if(length>64){
> return "";
> }
> if(length<64){
> for (int i = 0; i < (64-length); i++) {
> str = "0"+str;
> }
> }
> char[] strArr = str.toCharArray();
> StringBuffer sb = new StringBuffer();
> byte[] bytes = new byte[32];
> int i = 0;
> for (char ch : strArr){
> sb.append(ch);
> if(sb.toString().length()>1){
> byte info = (byte)Integer.parseInt(sb.toString(),16);
> bytes[i] = info;
> i++;
> sb = new StringBuffer();
> }
> }
> return Base64.encode(bytes);
> }
> public static String strTo16(String s) {
> String str = "";
> for (int i = 0; i < s.length(); i++) {
> int ch = (int) s.charAt(i);
> String s4 = Integer.toHexString(ch);
> str = str + s4;
> }
> return str;
> }
> 有其他问题大家在一起沟通。

我尝试了这个方法，并且验证了一下，虽然可以导入imtoken，但是导入后的地址不相符
这是用createWallet方法生成的地址和私钥
地址f1j63uq762o5ww334qlfznq3ctmhoqpier5elhyga
私钥78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994
这是导入到imtoken的地址和私钥
地址f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq
私钥7b2254797065223a22736563703235366b31222c22507269766174654b6579223a2265506d6e71664b48766372754a4767565649364e446e666b32483255504779714e536f7055614c32535a513d227d

私钥是经过这种方法生成的
![image](https://user-images.githubusercontent.com/30950645/115545481-7126c780-a2d6-11eb-84cd-2f7d492ad7b6.png)

**Comment by fzx0824** [comment]
String privateKey ="78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994";
        ECKey ecKey = ECKey.fromPrivate(HexUtil.decodeHex(privateKey));
        byte[] privKeyBytes = ecKey.getPrivKeyBytes();
        byte[] pubKey = ecKey.getPubKey();
        String filAddress = byteToAddress(pubKey);
        System.out.println(filAddress);


        String privatekey = HexUtil.encodeHexStr(privKeyBytes);
        System.out.println(filAddress);
        System.out.println(privatekey);

 ECKey.fromPrivate(HexUtil.decodeHex(privateKey));  这个地方看下是不是用的HexUtil。
 我这边尝试地址是f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq

**Comment by paipaipaipai** [comment]
> ```
>     String privateKey ="78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994";
>     ECKey ecKey = ECKey.fromPrivate(HexUtil.decodeHex(privateKey));
>     byte[] privKeyBytes = ecKey.getPrivKeyBytes();
>     byte[] pubKey = ecKey.getPubKey();
>     String filAddress = byteToAddress(pubKey);
>     System.out.println(filAddress);
> 
> 
>     String privatekey = HexUtil.encodeHexStr(privKeyBytes);
>     System.out.println(filAddress);
>     System.out.println(privatekey);
> ```
> 
> ECKey.fromPrivate(HexUtil.decodeHex(privateKey)); 这个地方看下是不是用的HexUtil。
> 我这边尝试地址是f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq

用的是createWallet生成的私钥

**Comment by paipaipaipai** [comment]
> ```
>     String privateKey ="78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994";
>     ECKey ecKey = ECKey.fromPrivate(HexUtil.decodeHex(privateKey));
>     byte[] privKeyBytes = ecKey.getPrivKeyBytes();
>     byte[] pubKey = ecKey.getPubKey();
>     String filAddress = byteToAddress(pubKey);
>     System.out.println(filAddress);
> 
> 
>     String privatekey = HexUtil.encodeHexStr(privKeyBytes);
>     System.out.println(filAddress);
>     System.out.println(privatekey);
> ```
> 
> ECKey.fromPrivate(HexUtil.decodeHex(privateKey)); 这个地方看下是不是用的HexUtil。
> 我这边尝试地址是f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq

是的，我的公钥生成地址的方法写错了

**Comment by paipaipaipai** [comment]
> > ```
> >     String privateKey ="78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994";
> >     ECKey ecKey = ECKey.fromPrivate(HexUtil.decodeHex(privateKey));
> >     byte[] privKeyBytes = ecKey.getPrivKeyBytes();
> >     byte[] pubKey = ecKey.getPubKey();
> >     String filAddress = byteToAddress(pubKey);
> >     System.out.println(filAddress);
> > 
> > 
> >     String privatekey = HexUtil.encodeHexStr(privKeyBytes);
> >     System.out.println(filAddress);
> >     System.out.println(privatekey);
> > ```
> > 
> > 
> > ECKey.fromPrivate(HexUtil.decodeHex(privateKey)); 这个地方看下是不是用的HexUtil。
> > 我这边尝试地址是f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq
> 
> 是的，我的公钥生成地址的方法写错了

我在做从lotus格式转换成原生格式的方法，还差最后一步base64转码，请问有这个代码吗

**Comment by paipaipaipai** [comment]
![image](https://user-images.githubusercontent.com/30950645/115649496-0323e400-a35a-11eb-9868-3ef66b160b6d.png)

**Comment by paipaipaipai** [comment]
> ```
>     String privateKey ="78f9a7a9f287bdcaee246815548e8d0e77e4d87d943c6caa352a2951a2f64994";
>     ECKey ecKey = ECKey.fromPrivate(HexUtil.decodeHex(privateKey));
>     byte[] privKeyBytes = ecKey.getPrivKeyBytes();
>     byte[] pubKey = ecKey.getPubKey();
>     String filAddress = byteToAddress(pubKey);
>     System.out.println(filAddress);
> 
> 
>     String privatekey = HexUtil.encodeHexStr(privKeyBytes);
>     System.out.println(filAddress);
>     System.out.println(privatekey);
> ```
> 
> ECKey.fromPrivate(HexUtil.decodeHex(privateKey)); 这个地方看下是不是用的HexUtil。
> 我这边尝试地址是f1f4zzopuigiurftsbri5estbpzqhsjn3jh4mubwq

有关于convertToBase64的方法，有没有更优雅的工具类呢
![image](https://user-images.githubusercontent.com/30950645/115650767-7890b400-a35c-11eb-811f-da36b7fda196.png)
，多谢

**Comment by paipaipaipai** [comment]
我改进了方法
https://github.com/paipaipaipai/FilecoinJ/blob/ac1afa43bc98c115129a821e66ec501ba80c07af/src/main/java/com/filecoinj/handler/FilecoinHandler.java#L88-L111

![image](https://user-images.githubusercontent.com/30950645/115655365-bfcf7280-a365-11eb-9a96-80625c52d1be.png)

**Comment by paipaipaipai** [comment]
> 这个问题你解决了吗？

https://github.com/paipaipaipai/FilecoinJ/blob/ac1afa43bc98c115129a821e66ec501ba80c07af/src/main/java/com/filecoinj/handler/FilecoinHandler.java#L88-L111

已经解决

**Comment by xuehongyang** [comment]
> > 这个问题你解决了吗？
> 
> https://github.com/paipaipaipai/FilecoinJ/blob/ac1afa43bc98c115129a821e66ec501ba80c07af/src/main/java/com/filecoinj/handler/FilecoinHandler.java#L88-L111
> 
> 已经解决


好的，我看下
